name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
            Hello! Thank you so much for filing an issue that helps us to improve.

            If this is a bug report, please include relevant logs to help us debug the problem.
        pr-message: |
            You've made your first pull request - awesome! Let's collaborate to make this project even better
            
            If you're fixing a bug, please refer to the issue number in the description.

            If you are implementing a feature request, please check with the maintainers that the feature will be accepted first.
